# Port Scanner Client Configuration

# Server connection settings
server_url: "http://localhost:5000" # Change to your server address
client_port: 8080 # Port to listen on
client_host: "0.0.0.0" # Interface to bind to
# client_id: "CUSTOM_ID"  # Override auto-detected MAC address
# hostname: "scanner-01"  # Override auto-detected hostname

# Scan settings
chunk_size: 1  # Number of targets per chunk (adjust based on network speed)
per_target_timeout: 120  # Timeout per target in seconds
progress_report_interval: 10  # Send progress updates every N seconds

# Heartbeat and retry settings
heartbeat_interval: 60
check_approval_interval: 30
retry_attempts: 3
retry_delay: 5

# Scan range for this client (optional, e.g. '192.168.1.0/24')
scan_range: "192.168.1.0/28"
