# Port Scanner Client Configuration

# Server connection settings
server_url: "http://localhost:5000" # Change to your server address

# Scanning behavior
check_interval: 30 # How often to check for new tasks (seconds)
heartbeat_interval: 60 # How often to send heartbeat (seconds)
max_concurrent_scans: 2 # Maximum concurrent scans (not yet implemented)
progress_update_interval: 10 # How often to send progress updates during scan (seconds)

# Network resilience
retry_attempts: 3 # Number of retry attempts for failed requests
retry_delay: 5 # Delay between retry attempts (seconds)

# Scan defaults (can be overridden by server)
default_timeout: 300 # Default scan timeout (seconds)
default_ports: "1-1000" # Default port range if not specified

# Logging
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file: "client.log" # Optional: log to file
log_max_size: 10485760 # Max log file size in bytes (10MB)
log_backup_count: 5 # Number of backup log files to keep

# Performance tuning
nmap_max_parallelism: 100 # Maximum parallel probes for nmap
nmap_min_rate: 50 # Minimum packet rate for nmap

# Client identification (optional - will auto-detect if not set)
# client_id: "CUSTOM_ID"  # Override auto-detected MAC address
# hostname: "scanner-01"  # Override auto-detected hostname
