# Test Configuration for Port Scanner Client Agent #1

# Server connection settings
server_url: "http://server:5000" # Change to your server address

client_port: 8080
client_host: "172.20.0.100"
client_id: "rpi-test-client-001"
hostname: "rpi-docker-client-001"

# Scan settings
chunk_size: 1  # Number of targets per chunk (adjust based on network speed)
per_target_timeout: 120  # Timeout per target in seconds
progress_report_interval: 10  # Send progress updates every N seconds

# Heartbeat and retry settings
heartbeat_interval: 60
check_approval_interval: 30
retry_attempts: 3
retry_delay: 5

# Scan range for this client
scan_range: "172.20.0.0/28"
